name: Tests

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v7

      - name: Install GoogleTest
        run: sudo apt-get update && sudo apt-get install -y libgtest-dev

      - name: Configure
        run: cmake -S . -B build

      - name: Build library
        run: cmake --build build

      - name: Run tests
        run: ./build/nstd_tests
